### ISSUE TITLE
The requested URL returned error: 416

### ISSUE THREAD

**Issue by SuperEgg9562** [dev-academy-programme/orientation#18]
C:\WINDOWS\system32>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'eda/phase-zero' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'eda/phase-zero'
    default: URL: https://vagrantcloud.com/eda/phase-zero
==> default: Adding box 'eda/phase-zero' (v1.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/eda/boxes/phase-zero/versions/1.0.0/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
    default: Progress: 100% (Rate: 101/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 416

**Comment by SuperEgg9562** [comment]
Having trouble with the above, help

**Comment by SuperEgg9562** [comment]
Please

**Comment by don-smith** [comment]
@SuperEgg9562 It doesn't look like you're in the correct directory when you're running `vagrant up`. You should call this from the directory that has the `vagrantfile` in it.

**Comment by don-smith** [comment]
@SuperEgg9562 It looks like the download partially failed. Delete the `virtrualbox.box` file if you have one and try again. It should redownload the file and you should be good to go. I would also recommend you **not** do this in your `C:\WINDOWS\system32` folder. Somewhere in your home folder would be more appropriate.

**Comment by SuperEgg9562** [comment]
thank you so much mate. That worked wonders 👍
